version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node-red"
    schedule:
      interval: daily
      time: "06:00"
  - package-ecosystem: "docker"
    directory: "/node-red"
    schedule:
      interval: daily
      time: "06:00"
