---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-node-red"
  ADDON_SLUG: "node-red"
  ADDON_TARGET: "node-red"

  ADDON_ARMV7: "false"
  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/base-aarch64:2.3.2"
  ADDON_AMD64_BASE: "hassioaddons/base-amd64:2.3.2"
  ADDON_ARMHF_BASE: "hassioaddons/base-armhf:2.3.2"
  ADDON_I386_BASE: "hassioaddons/base-i386:2.3.2"
