---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-node-red"
  ADDON_SLUG: "node-red"
  ADDON_TARGET: "node-red"
  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/base-aarch64:5.0.3"
  ADDON_AMD64_BASE: "hassioaddons/base-amd64:5.0.3"
  ADDON_ARMHF_BASE: "hassioaddons/base-armhf:5.0.3"
  ADDON_ARMV7_BASE: "hassioaddons/base-armv7:5.0.3"
  ADDON_I386_BASE: "hassioaddons/base-i386:5.0.3"
